### ISSUE TITLE
Feature: TypeScript Support

### ISSUE THREAD

**Issue by Malix-Off** [jthegedus/svelte-adapter-firebase#210] opened 2023-03-12 09:30 UTC

**Comment by joefhall** [comment] 2023-06-12 10:06
+1 for Typescript support -- would love that, I haven't been able to get the adapter to work properly in my Typescript project

**Comment by jthegedus** [comment] 2023-06-18 14:27
Duplicate of #8

**Closed by jthegedus** 2023-06-18 14:27 UTC
Labels: enhancement

**Comment by Malix-Off** [comment] 2023-06-19 12:03
_Should be closed as duplicate (same state as not planned)_
